---
version: "3"

includes:
  go: https://raw.githubusercontent.com/osapi-io/osapi-io-taskfiles/refs/heads/main/go.yml
  docs:
    taskfile: https://raw.githubusercontent.com/osapi-io/osapi-io-taskfiles/refs/heads/main/docs.yml
    dir: ./docs
  bats:
    taskfile: https://raw.githubusercontent.com/osapi-io/osapi-io-taskfiles/refs/heads/main/bats.yml
    dir: ./test

tasks:
  deps:
    desc: Install dependencies
    cmds:
      - task: go:deps
      - task: bats:deps
      - task: docs:deps

  test:
    desc: Test all
    cmds:
      - task: linux:tune
      - task: go:test
      - task: bats:test

  generate:
    desc: Generate Go files by processing source
    cmds:
      - redocly join --prefix-tags-with-info-prop title -o internal/client/gen/api.yaml internal/api/*/gen/api.yaml
      - task: go:generate
      - task: docs:generate

  linux:tune:
    desc: Enable "unprivileged" ping
    platforms:
      - linux
    cmds:
      - sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
