// Code generated by MockGen. DO NOT EDIT.
// Source: ../provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	system "github.com/retr0h/osapi/internal/provider/system"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetHostname mocks base method.
func (m *MockProvider) GetHostname() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostname")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostname indicates an expected call of GetHostname.
func (mr *MockProviderMockRecorder) GetHostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostname", reflect.TypeOf((*MockProvider)(nil).GetHostname))
}

// GetLoadAverageStats mocks base method.
func (m *MockProvider) GetLoadAverageStats() (*system.LoadAverageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadAverageStats")
	ret0, _ := ret[0].(*system.LoadAverageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadAverageStats indicates an expected call of GetLoadAverageStats.
func (mr *MockProviderMockRecorder) GetLoadAverageStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadAverageStats", reflect.TypeOf((*MockProvider)(nil).GetLoadAverageStats))
}

// GetLocalDiskStats mocks base method.
func (m *MockProvider) GetLocalDiskStats() ([]system.DiskUsageStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalDiskStats")
	ret0, _ := ret[0].([]system.DiskUsageStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalDiskStats indicates an expected call of GetLocalDiskStats.
func (mr *MockProviderMockRecorder) GetLocalDiskStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalDiskStats", reflect.TypeOf((*MockProvider)(nil).GetLocalDiskStats))
}

// GetMemoryStats mocks base method.
func (m *MockProvider) GetMemoryStats() (*system.MemoryStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryStats")
	ret0, _ := ret[0].(*system.MemoryStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoryStats indicates an expected call of GetMemoryStats.
func (mr *MockProviderMockRecorder) GetMemoryStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryStats", reflect.TypeOf((*MockProvider)(nil).GetMemoryStats))
}

// GetUptime mocks base method.
func (m *MockProvider) GetUptime() (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUptime")
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUptime indicates an expected call of GetUptime.
func (mr *MockProviderMockRecorder) GetUptime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUptime", reflect.TypeOf((*MockProvider)(nil).GetUptime))
}
