# Copyright (c) 2024 John Dewey
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

---
openapi: 3.0.0
info:
  title: System Status API
  version: 1.0.0
  name: system_status
tags:
  - name: system_operations
    x-displayName: System
    description: Operations related to the system status endpoint
paths:
  /system/status:
    get:
      summary: Retrieve system status
      description: Get the current status of the system including hostname, uptime, load averages, memory, and disk usage.
      tags:
        - system_operations
      responses:
        '200':
          description: A JSON object containing the system's status information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatus'
        '500':
          description: Error retrieving system status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    LoadAverage:
      type: object
      description: The system load averages for 1, 5, and 15 minutes.
      properties:
        1min:
          type: number
          description: Load average for the last 1 minute.
          example: 0.32
        5min:
          type: number
          description: Load average for the last 5 minutes.
          example: 0.28
        15min:
          type: number
          description: Load average for the last 15 minutes.
          example: 0.25
      required:
        - 1min
        - 5min
        - 15min
    Memory:
      type: object
      description: Memory usage information.
      properties:
        total:
          type: integer
          description: Total memory in bytes.
          example: 8388608
        free:
          type: integer
          description: Free memory in bytes.
          example: 2097152
        used:
          type: integer
          description: Used memory in bytes.
          example: 4194304
      required:
        - total
        - free
        - used
    SystemStatus:
      type: object
      properties:
        hostname:
          type: string
          description: The hostname of the system.
          example: "my-linux-server"
        uptime:
          type: string
          description: The uptime of the system.
          example: "0 days, 4 hours, 1 minute"
        load_average:
          $ref: '#/components/schemas/LoadAverage'
        memory:
          $ref: '#/components/schemas/Memory'
        disk:
          type: object
          description: Local disk usage information.
          properties:
            total:
              type: integer
              description: Total disk space in bytes.
              example: 500000000000
            used:
              type: integer
              description: Used disk space in bytes.
              example: 250000000000
            free:
              type: integer
              description: Free disk space in bytes.
              example: 250000000000
          required:
            - total
            - used
            - free
      required:
        - hostname
        - uptime
        - load_average
        - memory
        - disk

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: A description of the error that occurred.
          example: "Failed to retrieve the system status."
        details:
          type: string
          description: Additional details about the error, specifying which component failed.
          example: "Failed to retrieve hostname."
        code:
          type: integer
          description: The error code.
          example: 500
      required:
        - error
        - code
