openapi: 3.0.0
info:
  title: OSAPI - A CRUD API for managing Linux systems
  description: |
    OSAPI is a lightweight, minimalistic RESTful API designed to manage and
    configure Linux systems as appliances. The API provides comprehensive
    management capabilities, including reading the current state of the system
    and making privileged, asynchronous changes to match a desired configuration
    state.

    OSAPI is built with pluggability and extensibility in mind, allowing it to
    adapt to different Linux distributions and environments by implementing
    custom handlers for various system operations.

    Key Features:
    - **RESTful API Design:** A RESTful approach for managing Linux systems,
      enabling clear and organized endpoints for system configurations,
      diagnostics, and state management.
    - **Pluggable Architecture:** Easily extend or replace components to suit
      different Linux environments. This flexibility allows users to customize
      behavior based on specific distribution requirements or operational needs.
    - **Task Queue for Privileged Actions:** Asynchronous task execution to
      perform system modifications securely, ensuring that changes are managed
      in a controlled and orderly manner.
    - **System Information Gathering:** Provides detailed system insights, such
      as OS details, hostname, and other environment-specific information,
      facilitating diagnostics and monitoring.
    - **CLI Equivalence:** All functionalities accessible via the API are also
      available through an equivalent command-line interface, making the tool
      adaptable to both programmatic and manual use cases.
    - **Written in Go:** The API and its supporting tools are written in Go,
      ensuring high performance, low resource usage, and easy cross-platform
      deployment.
  version: 1.0.0
  contact:
    url: https://github.com/retr0h/osapi
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:8080
    description: Mock API (local)
tags:
  - name: Minimal_ping_API_Endpoint_ping_operations
    x-displayName: Ping
    description: Operations related to the ping endpoint
  - name: System_Status_API_system_operations
    x-displayName: System
    description: Operations related to the system status endpoint
paths:
  /ping:
    get:
      summary: Retrieve ping status
      tags:
        - Minimal_ping_API_Endpoint_ping_operations
      responses:
        '200':
          description: ping response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
  /system/status:
    get:
      summary: Retrieve system status
      description: >-
        Get the current status of the system including hostname, uptime, load
        averages, memory, and disk usage.
      tags:
        - System_Status_API_system_operations
      responses:
        '200':
          description: A JSON object containing the system's status information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatus'
        '500':
          description: Error retrieving system status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    LoadAverage:
      type: object
      description: The system load averages for 1, 5, and 15 minutes.
      properties:
        1min:
          type: number
          description: Load average for the last 1 minute.
          example: 0.32
        5min:
          type: number
          description: Load average for the last 5 minutes.
          example: 0.28
        15min:
          type: number
          description: Load average for the last 15 minutes.
          example: 0.25
      required:
        - 1min
        - 5min
        - 15min
    Memory:
      type: object
      description: Memory usage information.
      properties:
        total:
          type: integer
          description: Total memory in bytes.
          example: 8388608
        free:
          type: integer
          description: Free memory in bytes.
          example: 2097152
        used:
          type: integer
          description: Used memory in bytes.
          example: 4194304
      required:
        - total
        - free
        - used
    Disk:
      type: object
      description: Local disk usage information.
      properties:
        name:
          type: string
          description: Disk identifier, e.g., "/dev/sda1".
          example: /dev/sda1
        total:
          type: integer
          description: Total disk space in bytes.
          example: 500000000000
        used:
          type: integer
          description: Used disk space in bytes.
          example: 250000000000
        free:
          type: integer
          description: Free disk space in bytes.
          example: 250000000000
      required:
        - name
        - total
        - used
        - free
    Disks:
      type: array
      description: List of local disk usage information.
      items:
        $ref: '#/components/schemas/Disk'
    SystemStatus:
      type: object
      properties:
        hostname:
          type: string
          description: The hostname of the system.
          example: my-linux-server
        uptime:
          type: string
          description: The uptime of the system.
          example: 0 days, 4 hours, 1 minute
        load_average:
          $ref: '#/components/schemas/LoadAverage'
        memory:
          $ref: '#/components/schemas/Memory'
        disks:
          $ref: '#/components/schemas/Disks'
      required:
        - hostname
        - uptime
        - load_average
        - memory
        - disks
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: A description of the error that occurred.
          example: Failed to retrieve the system status.
        details:
          type: string
          description: >-
            Additional details about the error, specifying which component
            failed.
          example: Failed to retrieve hostname.
        code:
          type: integer
          description: The error code.
          example: 500
      required:
        - error
        - code
x-tagGroups:
  - name: Minimal ping API Endpoint
    tags:
      - Minimal_ping_API_Endpoint_ping_operations
  - name: System Status API
    tags:
      - System_Status_API_system_operations
