// Code generated by MockGen. DO NOT EDIT.
// Source: ../provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ping "github.com/retr0h/osapi/internal/provider/network/ping"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// PingHost mocks base method.
func (m *MockProvider) PingHost(address string) (*ping.PingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingHost", address)
	ret0, _ := ret[0].(*ping.PingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PingHost indicates an expected call of PingHost.
func (mr *MockProviderMockRecorder) PingHost(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingHost", reflect.TypeOf((*MockProvider)(nil).PingHost), address)
}
