// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package dns_test

import (
	"errors"
	"log/slog"
	"os"
	"testing"

	"github.com/avfs/avfs"
	"github.com/avfs/avfs/vfs/failfs"
	"github.com/avfs/avfs/vfs/memfs"
	"github.com/stretchr/testify/suite"

	"github.com/osapi-io/osapi/internal/provider"
	"github.com/osapi-io/osapi/internal/provider/network/netplan/dns"
)

type DebianDockerPublicTestSuite struct {
	suite.Suite

	logger *slog.Logger
	fs     avfs.VFS
}

func (s *DebianDockerPublicTestSuite) SetupTest() {
	s.logger = slog.New(slog.NewTextHandler(os.Stdout, nil))
	s.fs = memfs.New()
}

func (s *DebianDockerPublicTestSuite) SetupSubTest() {
	s.SetupTest()
}

func (s *DebianDockerPublicTestSuite) TestGetResolvConfByInterface() {
	tests := []struct {
		name          string
		setupFS       func(fs avfs.VFS)
		overrideFS    func() avfs.VFS
		interfaceName string
		validateFunc  func(any, error)
	}{
		{
			name: "when resolv.conf has servers search domains and noise",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"# Generated by Docker\n"+
						"\n"+
						"nameserver 127.0.0.11\n"+
						"nameserver 8.8.8.8\n"+
						"search example.com local.lan\n"+
						"options ndots:0\n"+
						"malformed\n",
				), 0o644)
			},
			interfaceName: "eth0",
			validateFunc: func(got any, err error) {
				s.NoError(err)
				s.Equal(&dns.GetResult{
					DNSServers:    []string{"127.0.0.11", "8.8.8.8"},
					SearchDomains: []string{"example.com", "local.lan"},
				}, got)
			},
		},
		{
			name: "when no search domains defaults to root",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 8.8.8.8\n",
				), 0o644)
			},
			interfaceName: "eth0",
			validateFunc: func(got any, err error) {
				s.NoError(err)
				s.Equal(&dns.GetResult{
					DNSServers:    []string{"8.8.8.8"},
					SearchDomains: []string{"."},
				}, got)
			},
		},
		{
			name: "when multiple search lines uses last one",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 8.8.8.8\n"+
						"search first.com\n"+
						"search second.com third.com\n",
				), 0o644)
			},
			interfaceName: "eth0",
			validateFunc: func(got any, err error) {
				s.NoError(err)
				s.Equal(&dns.GetResult{
					DNSServers:    []string{"8.8.8.8"},
					SearchDomains: []string{"second.com", "third.com"},
				}, got)
			},
		},
		{
			name: "when resolv.conf does not exist",
			setupFS: func(_ avfs.VFS) {
				// Don't create the file
			},
			interfaceName: "eth0",
			validateFunc: func(_ any, err error) {
				s.Error(err)
				s.Contains(err.Error(), "failed to read /etc/resolv.conf")
			},
		},
		{
			name: "when read error during scan",
			overrideFS: func() avfs.VFS {
				base := memfs.New()
				_ = base.MkdirAll("/etc", 0o755)
				_ = base.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 8.8.8.8\n",
				), 0o644)

				ffs := failfs.New(base)
				_ = ffs.SetFailFunc(func(
					_ avfs.VFSBase,
					fn avfs.FnVFS,
					_ *failfs.FailParam,
				) error {
					if fn == avfs.FnFileRead {
						return errors.New("simulated read error")
					}
					return nil
				})

				return ffs
			},
			interfaceName: "eth0",
			validateFunc: func(_ any, err error) {
				s.Error(err)
				s.Contains(err.Error(), "failed to parse /etc/resolv.conf")
			},
		},
	}

	for _, tc := range tests {
		s.Run(tc.name, func() {
			fs := s.fs
			if tc.overrideFS != nil {
				fs = tc.overrideFS()
			} else {
				tc.setupFS(s.fs)
			}

			p := dns.NewDebianDockerProvider(s.logger, fs)
			tc.validateFunc(p.GetResolvConfByInterface(tc.interfaceName))
		})
	}
}

func (s *DebianDockerPublicTestSuite) TestUpdateResolvConfByInterface() {
	tests := []struct {
		name         string
		validateFunc func(any, error)
	}{
		{
			name: "returns ErrUnsupported for container",
			validateFunc: func(result any, err error) {
				s.Error(err)
				s.Nil(result)
				s.ErrorIs(err, provider.ErrUnsupported)
			},
		},
	}

	for _, tt := range tests {
		s.Run(tt.name, func() {
			p := dns.NewDebianDockerProvider(s.logger, s.fs)
			tt.validateFunc(p.UpdateResolvConfByInterface(
				[]string{"8.8.8.8"},
				[]string{"example.com"},
				"eth0",
				false,
			))
		})
	}
}

func (s *DebianDockerPublicTestSuite) TestDeleteNetplanConfig() {
	tests := []struct {
		name         string
		validateFunc func(bool, error)
	}{
		{
			name: "returns ErrUnsupported for container",
			validateFunc: func(result bool, err error) {
				s.Error(err)
				s.False(result)
				s.ErrorIs(err, provider.ErrUnsupported)
			},
		},
	}

	for _, tt := range tests {
		s.Run(tt.name, func() {
			p := dns.NewDebianDockerProvider(s.logger, s.fs)
			tt.validateFunc(p.DeleteNetplanConfig("eth0"))
		})
	}
}

func TestDebianDockerPublicTestSuite(
	t *testing.T,
) {
	suite.Run(t, new(DebianDockerPublicTestSuite))
}
