// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dns "github.com/retr0h/osapi/internal/provider/network/dns"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetResolvConf mocks base method.
func (m *MockProvider) GetResolvConf() (*dns.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResolvConf")
	ret0, _ := ret[0].(*dns.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResolvConf indicates an expected call of GetResolvConf.
func (mr *MockProviderMockRecorder) GetResolvConf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResolvConf", reflect.TypeOf((*MockProvider)(nil).GetResolvConf))
}

// SetResolvConf mocks base method.
func (m *MockProvider) SetResolvConf(arg0, arg1 []string, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResolvConf", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResolvConf indicates an expected call of SetResolvConf.
func (mr *MockProviderMockRecorder) SetResolvConf(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResolvConf", reflect.TypeOf((*MockProvider)(nil).SetResolvConf), arg0, arg1, arg2)
}
