/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  testSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          // id: 'sidebar/intro',
          dirName: "sidebar",
        },
      ],
    },
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "This is the API documentation for osapi.",
        slug: "/category/api"
      },
      // @ts-ignore
      items: require("./docs/gen/api/sidebar.js")
    },
    // {
    //   type: 'category',
    //   label: 'Docusaurus',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'doc2',
    //     },
    //     {
    //       type: 'doc',
    //       id: 'doc3',
    //     },
    //   ],
    // },
    // {
    //   type: 'link',
    //   label: 'Learn more',
    //   href: 'https://example.com',
    // },
  ],
  // docsSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: "sidebar",
  //   }
  // ],
  // openApiSidebar: [
  //   {
  //     type: "category",
  //     label: "API",
  //     link: {
  //       type: "generated-index",
  //       title: "API",
  //       description:
  //         "This is the API documentation for osapi.",
  //       slug: "/category/api"
  //     },
  //     // @ts-ignore
  //     items: require("./docs/gen/api/sidebar.js")
  //   },
  // ]
};

export default sidebars;
